on:
  pull_request:
    paths:
      - 'swagger.json'
jobs:
  hello_world_job:
      runs-on: ubuntu-latest
      name: A job to say hello
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Hello world action step
          id: hello
          uses: MohammedCh/kongAction@main
          with:
            directory-filename: 'swagger.json'
        - name: comment PR
          uses: unsplash/comment-on-pr@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            msg: echo "The diff is ${{ steps.hello.outputs.msg }}"
            check_for_duplicate_msg: false  # OPTIONAL